### ISSUE TITLE
https Einbindung fehlt

### ISSUE THREAD

**Issue by DrCarsonBeckett** [derUli/disqus-comments#1]
Hallo,

die https Einbindung fehlt. Dadurch wird auf https gesicherten Seiten das Disqus Modul nicht geladen.
Man muss dieses erst manuell bestätigen, dann ist die Seite aber nicht mehr gesichert (http statt https).

Viele Grüße

**Comment by derUli** [comment]
Der Fehler ist in disqus_for_articles Version 1.1 behoben.

https://extend.ulicms.de/disqus_for_articles.html
